name: 'Sync Upstream, ModifyDockerfile, DockerCI'

on:
  push:
    branches:
      - flux
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
      - name: Delete main branch if it exists
        run: |
          if git show-ref --quiet refs/heads/main; then
            git branch -d main
          fi
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.MINECRAFT_SYNC }}
          upstream_sync_branch: master
          upstream_sync_repo: itzg/docker-minecraft-server
          test_mode: false

  modify_dockerfile:
    runs-on: ubuntu-latest
    needs: sync_latest_from_upstream
    steps:
      - name: Clone repository and checkout master as main
        run: |
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})
          git checkout -b main origin/master
      - name: Modify Dockerfile
        run: |
          sed '/COPY --chmod=755 files\/auto \/auto/,$d' Dockerfile > temp_file && mv temp_file Dockerfile
          echo "COPY --chmod=755 files/auto /auto" >> Dockerfile
          echo "COPY flux_master.sh start_master_final.sh /" >> Dockerfile
          echo "RUN chmod +x /flux_master.sh /start_master_final.sh" >> Dockerfile
          # ... (rest of your Dockerfile modifications)
          echo "HEALTHCHECK --start-period=1m --interval=5s --retries=24 CMD mc-health" >> Dockerfile
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Modified Dockerfile using action"
      - name: Push changes to main branch
        run: git push origin main
      - name: Push changes to flux branch
        run: git push origin flux

  push_to_registry:
    needs: modify_dockerfile
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: flux

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: wirewrex/minecraft-server:flux
