name: 'Sync Upstream, ModifyDockerfile, DockerCI'

on:
  push:
    branches:
      - flux
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          ref: flux
          persist-credentials: true
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: flux
          target_repo_token: ${{ secrets.MINECRAFT_SYNC }}
          upstream_sync_branch: master
          upstream_sync_repo: itzg/docker-minecraft-server
          test_mode: false
