name: 'Sync Upstream, ModifyDockerfile, DockerCI'

on:
  push:
    branches:
      - flux
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          ref: flux
          persist-credentials: true
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: flux
          target_repo_token: ${{ secrets.MINECRAFT_SYNC }}
          upstream_sync_branch: master
          upstream_sync_repo: itzg/docker-minecraft-server
          test_mode: false

  push_to_registry:
    needs: sync_latest_from_upstream
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: flux

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: wirewrex/minecraft-server:flux
